# Generated by Django 4.1.1 on 2022-10-21 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=12, unique=True, verbose_name='RUC')),
                ('name', models.CharField(max_length=50, verbose_name='Razón Social')),
                ('district', models.CharField(max_length=50, verbose_name='Distrito')),
                ('type_client', models.CharField(max_length=20, verbose_name='Tipo de Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('symbol', models.CharField(max_length=4, verbose_name='Simbolo')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Moneda',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('list_products', models.CharField(max_length=200, verbose_name='Lista de Productos')),
                ('delivery_date', models.DateField(verbose_name='Fecha de Entrega')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Dirección de Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'db_table': 'order',
            },
        ),
    ]
