# Generated by Django 4.1.1 on 2022-10-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido'},
        ),
        migrations.AddField(
            model_name='order',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IGV'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Descuento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='list_products',
            field=models.CharField(max_length=500, verbose_name='Lista de Productos'),
        ),
    ]
